import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { randomUUID } from "node:crypto";

import type {
  HintAgentBackend,
  HintBackendInput,
  HintBackendOutput,
} from "../backend";
import {
  SYSTEM_PROMPT,
  buildUserPrompt,
  composeHints,
  parseHintResponse,
} from "../hint";

// ============================================================
// ManualBackend — no model call, no API key. Two-phase use:
//
//   1. renderPrompt(input)  — writes a self-contained prompt file
//                             the user can paste into any chat AI
//                             (Claude.ai, ChatGPT, Gemini, ...).
//
//   2. run(input)           — reads the user-saved JSON response,
//                             composes AnomalyHints, returns the
//                             same shape AnthropicBackend returns.
//
// Same prompt body as AnthropicBackend (system + user concatenated
// into one paste-friendly text), so the prompt is tuned in exactly
// one place and works on every backend.
// ============================================================

export interface ManualBackendOptions {
  promptsDir: string;
  responsesDir: string;
}

const PASTE_DIVIDER = "---------------------- PASTE BELOW THIS LINE ----------------------";

export class ManualBackend implements HintAgentBackend {
  readonly name = "manual";

  constructor(private readonly opts: ManualBackendOptions) {}

  promptPath(source: string): string {
    return resolve(this.opts.promptsDir, `hint-${source}.md`);
  }

  responsePath(source: string): string {
    return resolve(this.opts.responsesDir, `hint-${source}.json`);
  }

  // Phase 1 — pure file write, no network, no model.
  renderPrompt(input: HintBackendInput): string {
    const userPrompt = buildUserPrompt({
      source: input.chunk.source,
      events: input.parsedEvents,
      time_range_start: input.chunk.time_range_start,
      time_range_end: input.chunk.time_range_end,
    });
    const path = this.promptPath(input.chunk.source);
    mkdirSync(dirname(path), { recursive: true });

    const responseRel = `cli-manual/responses/hint-${input.chunk.source}.json`;
    const body = `# Hint agent — ${input.chunk.source} stream (CLI regression flow)

This file is auto-generated by \`npm run hint:render\`. Do not edit.

> **Note:** the primary Stage 1 surface is the web app (\`npm run dev\`
> or \`npx vite preview --host 127.0.0.1\` after \`npm run build\`).
> This CLI flow exists for dev / CI prompt-regression testing, not as
> the main product workflow.

## What to do

1. Open your chat AI (Claude.ai, ChatGPT, Gemini, or any other).
2. Paste **everything below the divider** as a single message.
3. The AI will reply with a JSON object describing anomalies found in this stream.
4. Save the JSON (just the object — no markdown fences, no commentary) to:

       ${responseRel}

5. Repeat for the other two streams (\`hint-edge.md\`, \`hint-identity.md\`, \`hint-api.md\`).
6. Once all three response files are saved, run \`npm run hint:verify\`.

If your chat supports a downloadable artifact, file, or canvas (Claude.ai artifacts, ChatGPT canvas), the AI can put the JSON there directly — name it \`hint-${input.chunk.source}.json\`. Otherwise copy the JSON out of the code block in the chat reply.

${PASTE_DIVIDER}

${SYSTEM_PROMPT}

${userPrompt}
`;
    writeFileSync(path, body, "utf-8");
    return path;
  }

  // Phase 2 — reads the response file, composes hints. No network.
  async run(input: HintBackendInput): Promise<HintBackendOutput> {
    const path = this.responsePath(input.chunk.source);
    if (!existsSync(path)) {
      throw new Error(
        `Response file not found: ${path}\n` +
          `Run \`npm run hint:render\` first, paste the prompt at cli-manual/prompts/hint-${input.chunk.source}.md\n` +
          `into your chat AI, then save the AI's reply to the path above.`,
      );
    }
    const rawText = readFileSync(path, "utf-8");
    const rawHints = parseHintResponse(rawText);
    const agentRunId = randomUUID();
    const now = new Date().toISOString();
    const hints = composeHints({
      rawHints,
      chunkId: input.chunk.id,
      pipelineRunId: input.pipelineRunId,
      agentRunId,
      parsedEvents: input.parsedEvents,
      createdAt: now,
    });
    return { rawText, rawHints, hints, agentRunId };
  }
}
